import { useFonts } from "expo-font";
import { Dispatch, SetStateAction, useState } from "react";
import { Image, StyleSheet, View } from "react-native";
import DropDownPicker from "react-native-dropdown-picker";

type Props = {
  value: string | null;
  setValue: Dispatch<SetStateAction<null>>;
};

export default function FilterByYear({ value, setValue }: Props) {
  const [open, setOpen] = useState(false);
  // these could be generated by the API
  const [items, setItems] = useState([
    { label: "Filter by year", value: "noValue" },
    { label: "2006", value: "2006" },
    { label: "2007", value: "2007" },
    { label: "2008", value: "2008" },
    { label: "2009", value: "2009" },
    { label: "2011", value: "2011" },
    { label: "2012", value: "2012" },
    { label: "2013", value: "2013" },
    { label: "2014", value: "2014" },
    { label: "2015", value: "2015" },
    { label: "2016", value: "2016" },
    { label: "2017", value: "2017" },
    { label: "2018", value: "2018" },
    { label: "2019", value: "2019" },
    { label: "2020", value: "2020" },
  ]);

  const [loaded] = useFonts({
    bold: require("../../assets/font/BrandonGrotesque-Bold.ttf"),
  });

  if (!loaded) {
    return null;
  }
  return (
    // this was not fun
    <DropDownPicker
      style={styles.buttonContainer}
      placeholder="Filter by Year"
      open={open}
      value={value}
      items={items}
      setOpen={setOpen}
      setValue={setValue}
      setItems={setItems}
      textStyle={styles.buttonText}
      listItemLabelStyle={{
        color: "#000",
        fontFamily: "bold",
        zIndex: 10000,
      }}
      dropDownContainerStyle={{
        width: 180,
        zIndex: 10000,
      }}
      ArrowDownIconComponent={() => {
        return (
          <Image
            style={styles.icon}
            source={require("../../assets/icon/select.png")}
          />
        );
      }}
      ArrowUpIconComponent={() => {
        return (
          <Image
            style={styles.icon}
            source={require("../../assets/icon/selectUp.png")}
          />
        );
      }}
    />
  );
}

const styles = StyleSheet.create({
  buttonContainer: {
    margin: 20,
    paddingHorizontal: 20,
    width: 180,
    height: 50,
    backgroundColor: "#215184",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    borderColor: "#215184",
    borderRadius: 0,
  },
  buttonText: {
    color: "white",
    fontSize: 17,
    fontFamily: "bold",
  },
  icon: {
    width: 12,
    height: 6,
  },
});
